# Generated by Django 4.1.7 on 2023-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_website_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.URLField(),
        ),
    ]
