# Generated by Django 4.1.7 on 2023-06-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.brand')),
            ],
            options={
                'verbose_name_plural': 'Brand Statistics',
                'ordering': ('search_count',),
            },
        ),
    ]
