# Generated by Django 4.1.7 on 2023-06-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_brandstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandstatistics',
            options={'ordering': ['-search_count'], 'verbose_name_plural': 'Brand Statistics'},
        ),
    ]
