# Generated by Django 4.1.7 on 2023-06-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_brandstatistics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('convert_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_currency', to='main_app.currency')),
                ('convert_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_currency', to='main_app.currency')),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rates',
            field=models.ManyToManyField(through='main_app.ExchangeRate', to='main_app.currency'),
        ),
    ]
