# Generated by Django 4.1.7 on 2023-06-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_currency_exchangerate_currency_exchange_rates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
