# Generated by Django 4.1.7 on 2023-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_currency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_upd_time', models.DateTimeField()),
                ('currencies_upd_time', models.DateTimeField()),
            ],
        ),
    ]
