# Generated by Django 4.1.7 on 2023-06-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_updatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandstatistics',
            old_name='name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.currency'),
            preserve_default=False,
        ),
    ]
