# Generated by Django 4.1.7 on 2023-07-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_product_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(default='static/placeholder.png', max_length=512),
            preserve_default=False,
        ),
    ]
